name: Create Release for Project

on:
  workflow_call:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-release:
    uses: gh-shared/gh-shared/.github/workflows/create-release.yml@master
    with:
      version: ${{ inputs.version || github.ref_name }}
      repository: ${{ github.repository }}
    secrets:
      repo_token: ${{ secrets.GITHUB_TOKEN }}

  build-and-package:
    needs: create-release
    uses: ./.github/workflows/build-and-package.yml
    with:
      version: ${{ inputs.version || github.ref_name }}